(()=>{var e={};e.id=310,e.ids=[310],e.modules={2934:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external.js")},5403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},4580:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external.js")},4749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},5869:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},1017:e=>{"use strict";e.exports=require("path")},7310:e=>{"use strict";e.exports=require("url")},4761:(e,t,i)=>{"use strict";i.r(t),i.d(t,{GlobalError:()=>n.a,__next_app__:()=>m,originalPathname:()=>u,pages:()=>p,routeModule:()=>h,tree:()=>d});var r=i(3137),o=i(4647),a=i(4183),n=i.n(a),s=i(1775),c={};for(let e in s)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(c[e]=()=>s[e]);i.d(t,c);let l=r.AppPageRouteModule,d=["",{children:["privacy-policy",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(i.bind(i,2603)),"/home/runner/work/mindfiredigital.github.io/mindfiredigital.github.io/src/app/privacy-policy/page.tsx"]}]},{metadata:{icon:[async e=>(await Promise.resolve().then(i.bind(i,3881))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}]},{layout:[()=>Promise.resolve().then(i.bind(i,641)),"/home/runner/work/mindfiredigital.github.io/mindfiredigital.github.io/src/app/layout.tsx"],"not-found":[()=>Promise.resolve().then(i.t.bind(i,1918,23)),"next/dist/client/components/not-found-error"],metadata:{icon:[async e=>(await Promise.resolve().then(i.bind(i,3881))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}],p=["/home/runner/work/mindfiredigital.github.io/mindfiredigital.github.io/src/app/privacy-policy/page.tsx"],u="/privacy-policy/page",m={require:i,loadChunk:()=>Promise.resolve()},h=new l({definition:{kind:o.x.APP_PAGE,page:"/privacy-policy/page",pathname:"/privacy-policy",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:d}})},359:(e,t,i)=>{Promise.resolve().then(i.t.bind(i,1297,23))},2603:(e,t,i)=>{"use strict";i.r(t),i.d(t,{default:()=>__WEBPACK_DEFAULT_EXPORT__});var r=i(8144),o=i(4602),a=i.n(o);i(3830);let n=[{title:"PERSONAL IDENTIFICATION INFORMATION",description:`We may collect personal identification information from Users in a
       variety of ways, including, but not limited to, when Users visit our
       site, register on the site, place a request, and in connection with
       other activities, services, features or resources we make available on
       our Site. Users may be asked for, as appropriate, name, email address,
       mailing address, phone number. Users may, however, visit our Site
       anonymously. We will collect personal identification information from
       Users only if they voluntarily submit such information to us. Users can
       always refuse to supply personal identification information, except that
       it may prevent them from engaging in certain Site related activities.`},{title:"NON-PERSONAL IDENTIFICATION INFORMATION",description:`We may collect non-personal identification information about Users
        whenever they interact with our Site. Non-personal identification
        information may include the browser name, the type of computer and
        technical information about Users’ means of connection to our Site, such
        as the operating system, the Internet service provider utilised, and
        other similar information.`},{title:"WEB BROWSER COOKIES",description:`Our Site may use “cookies” to enhance User experience. User’s web
        browser places cookies on their hard drive for record-keeping purposes
        and sometimes to track information about them. User may choose to set
        their web browser to refuse cookies, or to alert you when cookies are
        being sent. If they do so, note that some parts of the Site may not
        function properly.`},{title:"HOW WE PROTECT YOUR INFORMATION",description:`We adopt appropriate data collection, storage and processing practices
        and security measures to protect against reauthorized access,
        alteration, disclosure or destruction of your personal information
        stored on our site. Sensitive and private data exchange between the Site
        and its Users happens over a SSL secured communication channel.`},{title:"SHARING YOUR PERSONAL INFORMATION",description:`We may share information if we think we have to in order to comply with
        the law or to protect ourselves. We will share information to respond to
        a court order or subpoena. We may also share it if a government agency
        or investigatory body requests. Or, we might also share information when
        we are investigating potential fraud.`},{title:"CHANGES TO THIS PRIVACY POLICY",description:`Mindfire Digital GitHub has the discretion to update this privacy policy
        at any time. We encourage Users to frequently check this page for any
        changes to stay informed about how we are helping to protect the
        personal information we collect. You acknowledge and agree that it is
        your responsibility to review this privacy policy periodically and
        become aware of modifications.`},{title:"JURISDICTION",description:`If you choose to visit the website, your visit and any dispute over
        privacy is subject to this Policy and the website’s terms of use. In
        addition to the foregoing, any disputes arising under this Policy shall
        be governed by the laws of India.`}],__WEBPACK_DEFAULT_EXPORT__=()=>(0,r.jsxs)("div",{className:"max-w-4xl mx-auto my-10 px-6",children:[(0,r.jsxs)("p",{className:"tracking-wider text-mindfire-content-p-text-color",children:["This Privacy Policy governs the manner in which mindfiredigital.github.io collects, uses, maintains and discloses information collected from users (each, a “User”) of the"," ",r.jsx(a(),{href:"https://mindfiredigital.github.io/",className:"text-mf-red hover:text-blue-400",children:"https://mindfiredigital.github.io/"})," ","website (“Site”). This privacy policy applies to the Site and all products and services offered by Mindfire Digital GitHub."]}),n.map(({title:e,description:t},i)=>(0,r.jsxs)("div",{children:[r.jsx("h3",{className:"mt-10 mb-2 text-mindfire-content-p-text-color font-semibold text-lg tracking-wider",children:e}),r.jsx("p",{className:"tracking-wider text-mindfire-content-p-text-color",children:t})]},i))]})},3881:(e,t,i)=>{"use strict";i.r(t),i.d(t,{default:()=>__WEBPACK_DEFAULT_EXPORT__});var r=i(6885);let __WEBPACK_DEFAULT_EXPORT__=e=>{let t=(0,r.fillMetadataSegment)(".",e.params,"favicon.ico");return[{type:"image/x-icon",sizes:"32x32",url:t+""}]}}};var t=require("../../webpack-runtime.js");t.C(e);var __webpack_exec__=e=>t(t.s=e),i=t.X(0,[248,885,255],()=>__webpack_exec__(4761));module.exports=i})();