name: Check Commitlint

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  check-commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run commitlint check
        run: npx --no -- commitlint --edit "$1"
